contest/contest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls', namespace='tasks')),
    path('theory/', include('theory.urls', namespace='theory')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

contest/tasks/urls.py
from django.conf.urls.static import static
from django.urls import path

from .views import *

app_name = 'tasks'

urlpatterns = [
    path('', index, name='index'),
    path('tasks/all/', all_tasks_page, name='tasks_all'),
    path('tasks/<slug:slug>/', task_page, name='task'),
    path('profile/<username>/', profile, name='profile'),
    path('profile/<username>/edit/', profile_edit, name='profile_edit'),
    path("profile/<str:username>/follow/", profile_follow,
         name="profile_follow"),
    path("profile/<str:username>/unfollow/", profile_unfollow,
         name="profile_unfollow"),
    path('tasks/<slug:slug>/talks/', task_talks, name='task_talks'),
    path(
        'tasks/<slug:slug>/talks/comment/<int:pk>/like/',
        comment_like,
        name='comment_like'
    ),
    path(
        'tasks/<slug:slug>/talks/comment/<int:pk>/unlike/',
        comment_unlike,
        name='comment_unlike'
    ),
]

contest/theory/urls.py
from django.urls import path

from .views import *


app_name = 'theory'

urlpatterns = [
    path('hash/', theory_hash, name='hash')
]

contest/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView)
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

contest/templates/includes/footer.html
<footer class="footer">
  <div class="container">
    <p>© 2022
      <span>Contest</span>app</p>
  </div>
</footer>

contest/templates/includes/form_base.html
{% csrf_token %}
{% if form.non_field_errors %}
  <div class="errors">
    {% for error in form.non_field_errors %}
      <span>
        {{ error|escape }}
      </span>
      <br/>
    {% endfor %}
  </div>
  {% endif %}
{% for field in form %}
  <div class="field" {% if field.field.required %} aria-required="false" {% else %} {% endif %}>
    <label for="{{ field.id_for_label }}">
      {{field.label}}
      {% if field.field.required %}
        <span class="required">*</span>
      {% endif %}
    </label>
    <div class="input__wrapper">
      {{ field }}
    </div>
    {% if field.errors %}
      <div class="errors">
        {% for error in field.errors %}
          <span>
            {{ error|escape }}
          </span>
          <br/>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endfor %}

contest/templates/includes/header.html
<header>
  <nav class="header">
    <div class="container">
      <div class="header__wrapper">
        <a href="{% url 'tasks:index' %}">
          <div class='header__logo logo'>
            <span>Contest</span>App
          </div>
        </a>

        {% with request.resolver_match.view_name as view_name %}
          <ul class="header__links">
            <a href="{% url 'tasks:tasks_all' %}">
              <li class="header__links-item {% if request.resolver_match.view_name  == 'tasks:tasks_all' %}active{% endif %}">
                Задания
              </li>
            </a>
            <a href="{% url 'theory:hash' %}">
              <li class="header__links-item {% if request.resolver_match.view_name  == 'theory:hash' %}active{% endif %}">
                Теория
              </li>
            </a>
          </ul>
          {% if request.user.is_authenticated %}
            <div class="header__user">
              <a href="{% url 'tasks:profile' user.username %}">
                <div class="user">{{ user.username }}</div>
              </a>
            </div>
          {% else %}
            <div class="header__auth">
              <a href="{% url 'users:login' %}">
                <div class="btn btn--trancsparent {% if request.resolver_match.view_name  == 'users:login' %}active{% endif %}">
                  Войти
                </div>
              </a>
              <a href="{% url 'users:signup' %}">
                <div class="btn btn--accent{% if request.resolver_match.view_name  == 'users:signup' %}active{% endif %}">
                  Регистрация
                </div>
              </a>
            </div>
          {% endif %}
        {% endwith %}
        </div>
      </div>
    </div>
  </nav>
</header>