contest/contest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls', namespace='tasks')),
    path('theory/', include('theory.urls', namespace='theory')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

contest/tasks/urls.py
from django.conf.urls.static import static
from django.urls import path

from .views import *

app_name = 'tasks'

urlpatterns = [
    path('', index, name='index'),
    path('tasks/all/', all_tasks_page, name='tasks_all'),
    path('tasks/<slug:slug>/', task_page, name='task'),
    path('profile/<username>/', profile, name='profile'),
    path('profile/<username>/edit/', profile_edit, name='profile_edit'),
    path("profile/<str:username>/follow/", profile_follow,
         name="profile_follow"),
    path("profile/<str:username>/unfollow/", profile_unfollow,
         name="profile_unfollow"),
    path('tasks/<slug:slug>/talks/', task_talks, name='task_talks'),
    path(
        'tasks/<slug:slug>/talks/comment/<int:pk>/like/',
        comment_like,
        name='comment_like'
    ),
    path(
        'tasks/<slug:slug>/talks/comment/<int:pk>/unlike/',
        comment_unlike,
        name='comment_unlike'
    ),
]

contest/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView)
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

contest/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Category(models.Model):
    title = models.CharField(
        max_length=200,
        db_index=True,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='URL'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['-id']


class Flexibility(models.Model):
    title = models.CharField(
        max_length=200,
        db_index=True,
        verbose_name='Сложность'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='URL'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сложность'
        verbose_name_plural = 'Сложности'
        ordering = ['-id']


class Task(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название',
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        db_index=True,
        verbose_name='URL',
    )
    content = models.TextField(verbose_name='Описание задания')
    time_create = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    time_update = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата обновления',
    )
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано',
    )
    function_name = models.TextField(verbose_name='Название функции')
    task_rating = models.IntegerField(
        default=10,
        verbose_name='Рейтинг задания'
    )
    flexibility = models.ForeignKey(
        Flexibility,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='tasks',
        verbose_name='Сложность'
    )
    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='tasks',
        verbose_name='Категория',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='tasks',
        verbose_name='Автор',
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tasks:task', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'
        ordering = ['-time_create']


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE,
                             related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="comments")
    text = models.TextField()
    created = models.DateTimeField("Время создания", auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="following")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="followers")


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='who_likes')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE,
                                related_name='like_comment')

contest/tasks/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment, Follow


class AnswerForm(forms.Form):
    decision = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 45, 'rows': 35})
    )


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Добавить комментарий'}
        help_texts = {'text': 'Текст комментария'}


class FollowForm(ModelForm):
    class Meta:
        model = Follow
        labels = {'user': 'Подписка на:', 'author': 'Автор записи'}
        fields = ['user']

contest/tasks/views.py
import logging
from importlib import import_module

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Exists, OuterRef
from django.shortcuts import get_object_or_404, redirect, render

from users.forms import ProfileForm, UpdateUserForm
from users.models import UserActions, Profile, UsersSolvedTasks
from .forms import AnswerForm, CommentForm
from .models import Comment, Follow, Like, Task
from .utils import action_collect, uniq_action_collect

User = get_user_model()


def index(request):
    template = 'tasks/index.html'
    top_users = Profile.objects.all(
    ).order_by(
        '-rating'
    )[:settings.TOP_RANK_PLAYERS_LIMIT].select_related('user')

    context = {
        'top_users': top_users,
        'title': 'Контест апп'
    }
    if request.user.is_authenticated:
        user = request.user

        authors = User.objects.filter(
            pk__in=Follow.objects.filter(
                user=user).values_list('author', flat=True))

        actions = UserActions.objects.filter(
            user__in=authors
        )[:settings.INDEX_PAGE_MAX_ACTIONS_COUNT].prefetch_related('user')

        context['actions'] = actions

    return render(request, template, context=context)


def all_tasks_page(request):
    template = 'tasks/tasks_all.html'
    tasks = Task.objects.filter(is_published=True)
    if request.user.is_authenticated:
        tasks = tasks.annotate(is_solved=Exists(UsersSolvedTasks.objects.filter(
            user=request.user, task=OuterRef('pk')
        )))
    context = {
        'tasks': tasks,
        'title': 'Задания',
    }
    return render(request, template, context=context)


@login_required
def task_page(request, slug):
    template = 'tasks/task_detail.html'
    task = get_object_or_404(Task, slug=slug)
    form = AnswerForm(
        request.POST or None,
        initial={'decision': task.function_name}
    )
    context = {
        'form': form,
        'task': task,
        'title': f'Задание {slug}'
    }
    if request.method == 'POST':
        with open(f'tasks/task_solutions/{request.user}_{slug}.py', 'w') as f:
            f.write(request.POST['decision'].replace('\n', ''))

        module_test_name = f'tasks.task_tests.test_{slug}'
        module_test = import_module(module_test_name)
        module_solution_name = f'tasks.task_solutions.{request.user}_{slug}'
        try:
            module_solution = import_module(module_solution_name)
            answer = module_test.testing(
                module_test.tests,
                module_solution.solution
            )
        except Exception as err:
            answer = err

        logger = logging.getLogger()
        logger.error(answer)

        context['answer'] = answer
        if answer == 'Тесты пройдены!':

            user = request.user
            ust = UsersSolvedTasks.objects.filter(
                user=user).filter(task=task).first()
            if not ust:
                ust = UsersSolvedTasks(
                    user=user,
                    task=task,
                    solved=False,
                    decision=''
                )
                ust.save()
            if not ust.solved:
                user.profile.rating += task.task_rating
                ust.solved = True
            ust.decision = request.POST['decision']
            ust.save()
            user.profile.save()
            description = f'выполнил(а) задание: {slug}!'
            action_url = f'/tasks/{slug}/'
            uniq_action_collect(user, description, action_url)

    return render(request, template, context=context)


def profile(request, username):
    template = 'tasks/profile.html'
    author = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    else:
        following = False
    user = request.user
    comments_count = Comment.objects.filter(author=author).count()
    tasks_solved = UsersSolvedTasks.objects.filter(
        user=author, solved=True
    ).count()
    likes_count = Comment.objects.filter(
        author=author
    ).aggregate(Count("like_comment"))
    context = {
        'user': user,
        'author': author,
        'following': following,
        'posts_count': comments_count,
        'tasks_solved': tasks_solved,
        'likes_count': likes_count['like_comment__count'],
    }
    return render(request, template, context=context)


@login_required
def profile_edit(request, username):
    template = 'tasks/profile_edit.html'
    user = get_object_or_404(User, username=username)
    if request.user.username != username:
        return redirect('tasks:profile', username)
    user_form = UpdateUserForm(request.POST or None, instance=user)
    profile_form = ProfileForm(
        request.POST, request.FILES or None, instance=user.profile
    )
    if user_form.is_valid() and profile_form.is_valid():
        user_form.save()
        profile_form.save()
        return redirect('tasks:profile', username)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, template, context=context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = User.objects.get(username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
        description = f'подписался(ась) на: {username}!'
        action_url = f'/profile/{username}/'
        action_collect(user, description, action_url)

    return redirect('tasks:profile', username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if is_follower.exists():
        is_follower.delete()
        description = f'отписался(ась) от: {username}!'
        action_url = f'/profile/{username}/'
        action_collect(user, description, action_url)

    return redirect('tasks:profile', username)


@login_required
def comment_like(request, slug, pk):
    comment = Comment.objects.get(pk=pk)
    like = Like.objects.filter(user=request.user, comment=comment)
    if not like.exists():
        Like.objects.create(user=request.user, comment=comment)
    return redirect('tasks:task_talks', slug)


@login_required
def comment_unlike(request, slug, pk):
    comment = Comment.objects.get(pk=pk)
    like = Like.objects.filter(user=request.user, comment=comment)
    if like.exists():
        like.delete()
    return redirect('tasks:task_talks', slug)


@login_required
def task_talks(request, slug):
    template = 'tasks/task_talks.html'
    task = get_object_or_404(Task, slug=slug)

    comments = task.comments.all().annotate(
        count_likes=Count('like_comment')
    ).annotate(is_request_user=Exists(
        Like.objects.filter(user=request.user, comment=OuterRef('pk')))
    ).select_related('author')

    form = CommentForm(request.POST or None)
    if form.is_valid():

        comment = form.save(commit=False)
        comment.author = request.user
        comment.task = task
        comment.save()
        description = f'написал(а) комментарий к заданию: {slug}!',
        action_url = f'/tasks/{slug}/talks/'
        action_collect(request.user, description, action_url)
        return redirect('tasks:task_talks', slug)
    context = {
        'task': task,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context=context)

contest/templates/tasks/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {{ title }}
{% endblock %}

{% block content %}
  <div class="home">
    <div class="home__leaderboard">
      <h2 class="home__leaderboard-title title">Топ-10 пользователей</h2>
      <p class="home__leaderboard-desc text">Рейтинг пользователя формируется на
        основне сложности решенных задач, в зависимости от их сложности</p>
      <div class="home__leaderboard-table">
        <table class='leaderboard'>
          <tbody>
          <tr class='leaderboard__row'>
            <th class='leaderboard__cell'>Ранк</th>
            <th class='leaderboard__cell'>Пользователь</th>
            <th class='leaderboard__cell'>Рейтинг</th>
          </tr>
          {% for profile in top_users %}
            <tr class='leaderboard__row'>
              <td class='leaderboard__cell'>
                #{{ forloop.counter }}
              </td>
              <td class='leaderboard__cell'>
                <a href="{% url 'tasks:profile' profile.user %}">
                  {{ profile.user }}
                </a>
              </td>
              <td class='leaderboard__cell'>{{ profile.rating }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="home__tabs">
      <button class='btn btn--trancsparent'>Новости</button>
      <button class='btn btn--trancsparent active'>Подписки</button>
    </div>

    <div class="home__content">
        {% for action in actions %}
          <div class="feed">
            {% if action.user.profile.avatar %}
            <img class="feed__avatar" src="{{ action.user.profile.avatar.url }}"
                 alt='user-icon'></img>
            {% else %}
            <img class="feed__avatar" src="{% static 'img/user-icon.png' %}"
                 alt='user-icon'></img>
            {% endif %}
            <div class="feed__wrapper">
              <a href="{% url 'tasks:profile' action.user %}">{{ action.user }}</a>
              <a href="{{ action.action_url }}">{{ action.description }}</a>
              <span>
                {{ action.time_create }}
              </span>
            </div>
          </div>
        {% endfor %}
    </div>
  </div>

{% endblock %}

contest/templates/tasks/profile.html
{% extends "base.html" %}
{% block title %}{{ author.username }}{% endblock %}

{% block content %}
  <div class="profile__container">
    <div class="profile__container__half">
      {% if author.profile.avatar %}
        <img width="300px" height="350px" src="{{ author.profile.avatar.url }}">
      {% endif %}
      {% if user != author %}
        {% if following %}
          <a href="{% url 'tasks:profile_unfollow' author.username %}">
            <div class="btn">Отписаться</div>
          </a>
        {% else %}
          <a href="{% url 'tasks:profile_follow' author.username %}">
            <div class="btn">Подписаться</div>
          </a>
        {% endif %}
      {% endif %}
    </div>
    <div class="profile__container__half">
      <p>рейтинг: {{ author.profile.rating }}</p>
      <p>количество постов: {{ posts_count }}</p>
      <p>количество решённых задач: {{ tasks_solved }}</p>
      <p>получено лайков: {{ likes_count }}</p>
      <a href="{% url 'users:logout' %}">
        <div class="btn"> Выйти</div>
      </a>
      {% if user == author %}
        <a href="{% url 'tasks:profile_edit' author %}">
          <div class="btn">Редактировать профиль</div>
        </a>
      {% endif %}
    </div>
  </div>
{% endblock %}

contest/templates/tasks/profile_edit.html
{% extends "base.html" %}
{% block title %}{{ author.username }}{% endblock %}
{% block content %}
  <div class="auth">
    <div class="auth__wrapper">
      <div class="auth__logo logo">
        <span>Contest</span>App
      </div>
      <div class="auth__form">
        <form class='form' method="post" enctype="multipart/form-data">
          {% include 'includes/form_base.html' with form=user_form %}
          {% include 'includes/form_base.html' with form=profile_form %}
          <button type="submit" class="btn auth__btn">
            Изменить
          </button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

contest/templates/tasks/task_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="task__container">
    <div class="task__container__half">
      {{ task.content }}
      <a href="{% url 'tasks:task_talks' task.slug %}">
        <div class="btn">Обусждения</div>
      </a>

    </div>
    <div class="task__container__half">
      <form method="post">
        {% include 'includes/form_base.html' %}
        {% if answer %}
          {{ answer }}
        {% endif %}
        <button type="submit" class="btn">
          Проверить
        </button>
      </form>
    </div>
  </div>
{% endblock %}

contest/templates/tasks/task_talks.html
{% extends "base.html" %}
{% block title %}Обсуждение задачи{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-body">
          {% for comment in comments %}
            <ul>
              <p><a href="{% url 'tasks:profile' comment.author %}">{{ comment.author }}</a></p>
              <p>{{ comment.text }}</p>
              <p>{{ comment.count_likes }}</p>
              <li class="list-group-item">
                {% if not comment.is_request_user %}
                  <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'tasks:comment_like' task.slug comment.pk %}" role="button">
                    Лайк
                  </a>
                {% else %}
                  <a
                    class="btn btn-lg btn-light"
                    href="{% url 'tasks:comment_unlike' task.slug comment.pk %}" role="button">
                    Отменить Лайк
                  </a>
                {% endif %}
              </li>
            </ul>
          {% endfor %}
          <form method="post">
            {% include 'includes/form_base.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Оставить комментарий
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

contest/templates/tasks/tasks_all.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="tasks">
    <div class="tasks__filters">
      <button class='btn dropdown'></button>
    </div>
    <table class="tasks-table">
      <tbody>
      <tr class='tasks-table__row'>
        <th class='tasks-table__cell'>Статус</th>
        <th class='tasks-table__cell'>Название</th>
        <th class='tasks-table__cell'>Сложность</th>
        <th class='tasks-table__cell'>Рейтинг</th>
      </tr>
      {% for task in tasks %}
        <tr class="tasks-table__row">
          <td class='tasks-table__cell'>
            {% if task.is_solved %}
              +
            {% else %}
              -
            {% endif %}
          </td>
          <td class='tasks-table__cell'>
            <a href="{% url 'tasks:task' task.slug %}">{{ task }}</a>
          </td>
          <td class='tasks-table__cell'>{{ task.flexibility }}</td>
          <td class='tasks-table__cell'>
            {{ task.task_rating }}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}